app = "realtime-chat-app"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT="8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [services.http_checks]
    grace_period = "5s"
    interval = "10s"
    method = "GET"
    path = "/"
    port = 8080
    protocol = "http"
    timeout = "2s"
    retries = 3
